"""Create user and todo tables

Revision ID: bb2ee5e2faf3
Revises: ad7cb6086daa
Create Date: 2025-06-24 16:59:38.451624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2ee5e2faf3'
down_revision = 'ad7cb6086daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('uid', name='uq_user_uid'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('task', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_uid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], name='fk_todo_user_uid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid', name='uq_todo_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    print("Downgrade disabled to protect schema.")
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('todo')
    #op.drop_table('user')
    # ### end Alembic commands ###
