"""Changed FK to user_uid and added status

Revision ID: dd041bc0287c
Revises: b44000436637
Create Date: 2025-06-25 10:46:04.608624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd041bc0287c'
down_revision = 'b44000436637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_uid', ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_uid', type_='unique')

    # ### end Alembic commands ###
